### PR TITLE
refactor: use async function instead of promise

### PR DESCRIPTION
**Pull request by popomore**

### CODE REVIEW

**Comment by JacksonTian** [comment]
Need support Node.js 6.

**Comment by JacksonTian** [comment]
Oh. I removed the nodejs 6 from travis list. = =

**Comment by JacksonTian** [comment]
Maybe I need to release major version.

**Comment by popomore** [comment]
Yeah, There is no engine specified in package.json, so I don’t know which version is supported by this module.

**Comment by popomore** [comment]
Updated

**Comment by JacksonTian** [comment]
landed in 1b1db348f0d601ee4d41908d88e3d1362c41b505

**Pull request closed without merging**
